baseURL = 'https://secularbeginnersgroup.github.io/'
languageCode = 'en-us'
title = 'Secular Beginners Group'

theme = 'hextra'

[[menu.main]]
  name = "Newcomer Packet"
  pageRef = "/newcomer_packet"
  weight = 2

[[menu.main]]
  name = "Meeting Format"
  pageRef = "/meeting_format"
  weight = 3

[[menu.main]]
  name = "Contact Us"
  pageRef = "/contact"
  weight = 4

# [[menu.main]]
#   name = "Blog"
#   pageRef = "/blog"
#   weight = 4

# [[menu.main]]
#   name = "Search"
#   weight = 4
#   params = { type = "search" }
